/*
 * Copyright or © or Copr.
 * 
 * This software is a computer program whose purpose is to generate random test
 * case from a template file describing the data model.
 * 
 * This software is governed by the CeCILL-B license under French law and
 * abiding by the rules of distribution of free software. You can use, modify
 * and/or redistribute the software under the terms of the CeCILL-B license as
 * circulated by CEA, CNRS and INRIA at the following URL
 * "http://www.cecill.info".
 * 
 * As a counterpart to the access to the source code and rights to copy, modify
 * and redistribute granted by the license, users are provided only with a
 * limited warranty and the software's author, the holder of the economic
 * rights, and the successive licensors have only limited liability.
 * 
 * In this respect, the user's attention is drawn to the risks associated with
 * loading, using, modifying and/or developing or reproducing the software by
 * the user in light of its specific status of free software, that may mean that
 * it is complicated to manipulate, and that also therefore means that it is
 * reserved for developers and experienced professionals having in-depth
 * computer knowledge. Users are therefore encouraged to load and test the
 * software's suitability as regards their requirements in conditions enabling
 * the security of their systems and/or data to be ensured and, more generally,
 * to use and operate it in the same conditions as regards security.
 * 
 * The fact that you are presently reading this means that you have had
 * knowledge of the CeCILL-B license and that you accept its terms.
 */
package com.taf.frame.panel.run;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;

import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextPane;

import com.taf.event.EventListener;
import com.taf.event.EventMethod;
import com.taf.event.ProcessReadyEvent;
import com.taf.frame.panel.RunPanel;
import com.taf.manager.EventManager;
import com.taf.manager.RunManager;
import com.taf.util.Consts;

/**
 * The TafConsolePanel is used in the {@link RunPanel} and displays the output
 * generated by the TAF generation using {@link JTextPane}.
 *
 * @see JPanel
 * @see RunPanel
 *
 * @author Adrien Jakubiak
 */
public class TafConsolePanel extends JPanel implements EventListener {

	/** The serial version UID. */
	private static final long serialVersionUID = -8939892289753953959L;

	/** The text pane. */
	private JTextPane textPane;

	/**
	 * Instantiates a new taf console panel.
	 */
	public TafConsolePanel() {
		this.setLayout(new GridBagLayout());

		GridBagConstraints c = Consts.getDefaultConstraint();
		c.gridwidth = GridBagConstraints.REMAINDER;
		c.gridheight = GridBagConstraints.REMAINDER;
		c.fill = GridBagConstraints.BOTH;
		c.weightx = 1;
		c.weighty = 1;

		textPane = new JTextPane();
		textPane.setEditable(false);
		textPane.setBackground(Consts.CONSOLE_BACKGROUND_COLOR);

		JScrollPane scrollPane = new JScrollPane(textPane);
		this.add(scrollPane, c);

		EventManager.getInstance().registerEventListener(this);
	}

	/**
	 * Handler for {@link ProcessReadyEvent}.
	 *
	 * @param event the event
	 */
	@EventMethod
	public void onProcessReady(ProcessReadyEvent event) {
		RunManager.getInstance().setTextPane(textPane);
	}

	@Override
	public void unregisterComponents() {
		// No children
	}

}
